### ISSUE TITLE
Propose removal of disused registerAsHost function

### ISSUE THREAD

**Issue by ltfschoen** [bricepollock/modular-architecture#2]
Can we remove method [registerAsHost](https://github.com/bricepollock/modular-architecture/blob/master/ModularApp/ModularApp/ApplicationFlowController.swift#L28-L30) in ApplicationFlowController.swift? When would it be used?

When launching the app, [registerHostApp](https://github.com/bricepollock/modular-architecture/blob/master/ModularApp/ModularApp/AppDelegate%2BRouting.swift#L20) is already being called during router configuration in AppDelegate+Routing.swift to register the ApplicationFlowController instance with Shared Module Router.

**Comment by bricepollock** [comment]
Updated so there is only one, thx!
